### ISSUE TITLE
Set up home page module to trigger program search with education level filter 

### ISSUE THREAD

**Issue by loibucket** [wwami-pipeline/NWHCP-front_end#32]

**Comment by CocoaCommander** [comment]
https://github.com/wwami-pipeline/NWHCP-front_end/commit/fa256c260fece0800649d00cd3a9abfac2018723

Backend needs some way to account for collegiate and higher level programs, currently does not have that capability

**Comment by CocoaCommander** [comment]
https://github.com/wwami-pipeline/NWHCP-front_end/commit/f0854c0cb159e5b041f9eb166670a574f8922748

Need to discuss why this data varies between certain elementary grades
